name: Setup and Build APK

on:
  push:
    branches:
      - master

jobs:
  setup-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Gradle
      uses: gradle/gradle-build-action@v1
      with:
        gradle-version: 7.3.1  # specify the Gradle version you want to install

    - name: Initialize Gradle Build
      run: |
        if [ ! -f build.gradle ]; then
          echo "apply plugin: 'com.android.application'" > build.gradle
          echo "android {" >> build.gradle
          echo "    compileSdkVersion 30" >> build.gradle
          echo "    defaultConfig {" >> build.gradle
          echo "        applicationId 'com.steepmax.expenses'" >> build.gradle
          echo "        minSdkVersion 8" >> build.gradle
          echo "        targetSdkVersion 30" >> build.gradle
          echo "        versionCode 13" >> build.gradle
          echo "        versionName '1.12'" >> build.gradle
          echo "    }" >> build.gradle
          echo "    buildTypes {" >> build.gradle
          echo "        release {" >> build.gradle
          echo "            minifyEnabled false" >> build.gradle
          echo "            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'" >> build.gradle
          echo "        }" >> build.gradle
          echo "    }" >> build.gradle
          echo "}" >> build.gradle
          echo "dependencies {" >> build.gradle
          echo "    implementation 'androidx.appcompat:appcompat:1.3.1'" >> build.gradle
          echo "    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'" >> build.gradle
          echo "}" >> build.gradle
          echo "rootProject.name = 'expense-tracker'" > settings.gradle
        fi
        gradle init

    - name: Generate Gradle Wrapper
      run: ./gradlew wrapper

    - name: Commit Gradle Wrapper
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -m "Add Gradle wrapper"
        git push

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        components: |
          build-tools;30.0.3
          platforms;android-30

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: build/outputs/apk/debug/app-debug.apk
